services:
  db:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5431:5432"

volumes:
  static_volume:
  uploads_volume:

networks:
  main-network: