"""empty message

Revision ID: 5d679d16d36f
Revises: 5f84e8b40e39
Create Date: 2024-11-26 04:58:07.650264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d679d16d36f'
down_revision: Union[str, None] = '5f84e8b40e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_data', sa.Column('seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_data', 'seo_description')
    # ### end Alembic commands ###
