"""new_field

Revision ID: 5f84e8b40e39
Revises: 2ec235992a18
Create Date: 2024-11-10 15:46:54.070293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f84e8b40e39'
down_revision: Union[str, None] = '2ec235992a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_data', sa.Column('start_bot_image_url_2', sa.VARCHAR(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_data', 'start_bot_image_url_2')
    # ### end Alembic commands ###
