"""empty message

Revision ID: d6110d96442f
Revises: d633f780909f
Create Date: 2024-11-06 13:00:33.978944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6110d96442f'
down_revision: Union[str, None] = 'd633f780909f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vpn_data_test_field', 'vpn_data', type_='unique')
    op.drop_constraint('uq_vpn_data_test_field_now', 'vpn_data', type_='unique')
    op.drop_column('vpn_data', 'test_field')
    op.drop_column('vpn_data', 'test_field_now')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_data', sa.Column('test_field_now', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vpn_data', sa.Column('test_field', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_vpn_data_test_field_now', 'vpn_data', ['test_field_now'])
    op.create_unique_constraint('uq_vpn_data_test_field', 'vpn_data', ['test_field'])
    # ### end Alembic commands ###
