"""empty message

Revision ID: ee2bae46c5dd
Revises: 
Create Date: 2024-10-30 18:24:07.465246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2bae46c5dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('vpn_title', sa.String(), nullable=False),
    sa.Column('header_title', sa.String(), nullable=False),
    sa.Column('header_description', sa.Text(), nullable=False),
    sa.Column('header_image_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('opportunity_block_title', sa.String(), nullable=False),
    sa.Column('opportunity_1_title', sa.String(), nullable=False),
    sa.Column('opportunity_1_short_description', sa.String(), nullable=False),
    sa.Column('opportunity_2_title', sa.String(), nullable=False),
    sa.Column('opportunity_2_short_description', sa.String(), nullable=False),
    sa.Column('opportunity_3_title', sa.String(), nullable=False),
    sa.Column('opportunity_3_short_description', sa.String(), nullable=False),
    sa.Column('opportunity_4_title', sa.String(), nullable=False),
    sa.Column('opportunity_4_short_description', sa.String(), nullable=False),
    sa.Column('opportunity_5_title', sa.String(), nullable=False),
    sa.Column('opportunity_5_short_description', sa.String(), nullable=False),
    sa.Column('opportunity_6_title', sa.String(), nullable=False),
    sa.Column('opportunity_6_short_description', sa.String(), nullable=False),
    sa.Column('global_coverage_main_title', sa.String(), nullable=False),
    sa.Column('global_coverage_title', sa.String(), nullable=False),
    sa.Column('global_coverage_description', sa.Text(), nullable=False),
    sa.Column('global_coverage_image_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('setup_security_title', sa.String(), nullable=False),
    sa.Column('setup_security_description', sa.Text(), nullable=False),
    sa.Column('setup_security_image_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('start_bot_image_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('start_bot_button_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('challenge_title', sa.String(), nullable=False),
    sa.Column('challenge_short_description', sa.Text(), nullable=False),
    sa.Column('challenge_background_image', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('license_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vpn_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vpn_data')
    # ### end Alembic commands ###
