name: Simple CI/CD for FastAPI

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on:
      ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Create .env for Develop Environment
      run: |
        echo "PRODUCTION_MODE=False" >> .env
        echo "DB_LINK=postgresql+asyncpg://test:test@db:5432/test" >> .env

    - name: Build Docker Image
      run: ./actions.sh local build



